# Generated by Django 3.2.3 on 2021-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(blank=True, max_length=100)),
                ('rate', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('tax_session', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
